# Generated by Django 4.1.13 on 2024-06-25 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noteapp', '0004_note_user_tag_user_alter_tag_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='added_by',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='author',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Quote',
        ),
    ]
